name: Build Fransom

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Setup NuGet.exe
      uses: nuget/setup-nuget@v1
      
    - name: Nuget restore 
      run: nuget restore Fransom.sln
            
    - name: Build
      run: msbuild Fransom.sln /p:Configuration=Release 
    
    - uses: actions/upload-artifact@master
      with:
        name: Fransom
        path: Fransom\bin\Release\Fransom.exe  
          
